version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: codedeploy-ecs-demo

phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - docker build -t ${IMAGE_URI} .
      - docker push ${IMAGE_URI}
  post_build:
    commands:
      - printf '{"ImageURI":"%s"}' ${IMAGE_URI} > imageDetail.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imageDetail.json
